import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { PassThrough } from 'node:stream'
import { describe, expect, it } from 'vitest'
import { drawnAnnotationEditor, geometryRevision, parseGeometry, serializeGeometry, validateGeometryPatch } from './drawn-annotation-editor'

/** Exercise the plugin through its narrow HTTP middleware, not its internals. */
function editorServer(root: string, output = 'styles/drawn-annotations.generated.css') {
  let middleware: ((request: any, response: any, next: () => void) => void) | undefined
  const plugin = drawnAnnotationEditor({ output })
  plugin.configResolved?.({ root })
  plugin.configureServer?.({ middlewares: { use(handler: typeof middleware) { middleware = handler } } })

  async function request(method: string, body?: unknown) {
    const input = new PassThrough() as PassThrough & { method: string, url: string }
    input.method = method
    input.url = '/__drawn-annotations'
    input.end(body === undefined ? undefined : JSON.stringify(body))
    let statusCode = 200
    const headers: Record<string, string> = {}
    let text = ''
    await new Promise<void>((resolve, reject) => {
      try {
        middleware?.(input, {
          setHeader(name: string, value: string) { headers[name] = value },
          set statusCode(value: number) { statusCode = value },
          get statusCode() { return statusCode },
          end(value: string) { text = value; resolve() },
        }, () => reject(new Error('editor middleware unexpectedly called next')))
      }
      catch (error) { reject(error) }
    })
    return { statusCode, headers, body: JSON.parse(text) }
  }

  return { request, plugin }
}

describe('DrawnAnnotation editor writer format', () => {
  it('serializes in a stable order with fixed precision', () => {
    const geometry = {
      zebra: { y: .2, x: .123456, width: .5 },
      alpha: { x: 1 },
    }
    expect(serializeGeometry(geometry)).toBe(`/* Generated by the DrawnAnnotation editor. Do not edit while Slidev is running. */

[data-drawn-annotation-id="alpha"] {
  --da-label-x: 1;
}
[data-drawn-annotation-id="zebra"] {
  --da-label-x: 0.1235;
  --da-label-y: 0.2;
  --da-label-width: 0.5;
}
`)
    expect(parseGeometry(serializeGeometry(geometry))).toEqual({
      alpha: { x: 1, y: undefined, width: undefined, x1: undefined, y1: undefined, x2: undefined, y2: undefined },
      zebra: { x: .1235, y: .2, width: .5, x1: undefined, y1: undefined, x2: undefined, y2: undefined },
    })
    expect(geometryRevision(geometry)).toBe(geometryRevision({ alpha: { x: 1 }, zebra: { x: .123456, y: .2, width: .5 } }))
  })

  it('only accepts safe IDs, known fields, and usable geometry', () => {
    expect(validateGeometryPatch({ okay: { x: 0, y: 1, width: .02, x1: .1, y1: .2, x2: .3, y2: .4 }, removed: null })).toEqual({ okay: { x: 0, y: 1, width: .02, x1: .1, y1: .2, x2: .3, y2: .4 }, removed: null })
    expect(validateGeometryPatch({ okay: { x: null, y: null, width: null } })).toEqual({ okay: { x: null, y: null, width: null } })
    expect(() => validateGeometryPatch({ 'not safe': { x: .5 } })).toThrow('invalid annotation ID')
    expect(() => validateGeometryPatch({ okay: { x: .5, css: 'nope' } })).toThrow('unknown property')
    expect(() => validateGeometryPatch({ okay: { width: .01 } })).toThrow('width')
    expect(() => validateGeometryPatch({ okay: { x: Number.NaN } })).toThrow('x')
  })

  it('round-trips manual connector endpoints and ignores malformed generated rules', () => {
    expect(parseGeometry('[data-drawn-annotation-id="okay"] { --da-label-x: 2; }\n[data-drawn-annotation-id="good"] { --da-label-y: .5; --da-connector-x1: .1; --da-connector-y1: .2; --da-connector-x2: .3; --da-connector-y2: .4; }')).toEqual({ good: { x: undefined, y: .5, width: undefined, x1: .1, y1: .2, x2: .3, y2: .4 } })
  })

  it('serves and atomically persists revision-guarded, property-wise patches', async () => {
    const root = await mkdtemp(join(tmpdir(), 'drawn-annotation-editor-'))
    try {
      const { request } = editorServer(root)
      const initial = await request('GET')
      expect(initial.statusCode).toBe(200)
      expect(initial.body.geometry).toEqual({})

      const saved = await request('POST', {
        expectedRevision: initial.body.revision,
        annotations: { note: { x: .25, y: .5, width: .3, x1: .1, y1: .2, x2: .3, y2: .4 } },
      })
      expect(saved.statusCode).toBe(200)
      expect(saved.body.geometry.note).toMatchObject({ x: .25, y: .5, width: .3, x1: .1, y1: .2, x2: .3, y2: .4 })
      expect(await readFile(join(root, 'styles/drawn-annotations.generated.css'), 'utf8')).toBe(serializeGeometry(saved.body.geometry))

      // A save response is the exact value CSS HMR will apply. The browser
      // uses it to clear its immediate drag preview after the stylesheet has
      // caught up, so raw pointer precision must not leak into this response.
      const rounded = await request('POST', {
        expectedRevision: saved.body.revision,
        annotations: { precise: { x: .123456, y: .987654 } },
      })
      expect(rounded.statusCode).toBe(200)
      expect(rounded.body.geometry.precise).toMatchObject({ x: .1235, y: .9877 })
      expect(await readFile(join(root, 'styles/drawn-annotations.generated.css'), 'utf8')).toContain('--da-label-x: 0.1235;')

      const patched = await request('POST', {
        expectedRevision: rounded.body.revision,

        annotations: { note: { width: .4, x1: null, y1: null, x2: null, y2: null } },
      })
      expect(patched.statusCode).toBe(200)
      expect(patched.body.geometry.note).toMatchObject({ x: .25, y: .5, width: .4 })
      expect(patched.body.geometry.note.x1).toBeUndefined()

      const stale = await request('POST', { expectedRevision: saved.body.revision, annotations: { note: { x: .1 } } })
      expect(stale.statusCode).toBe(409)
      expect(stale.body.geometry).toEqual(patched.body.geometry)
    }
    finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  it('serializes simultaneous writes so a stale revision cannot overwrite a newer edit', async () => {
    const root = await mkdtemp(join(tmpdir(), 'drawn-annotation-editor-'))
    try {
      const { request } = editorServer(root)
      const initial = await request('GET')
      const [first, second] = await Promise.all([
        request('POST', { expectedRevision: initial.body.revision, annotations: { first: { x: .1, y: .2 } } }),
        request('POST', { expectedRevision: initial.body.revision, annotations: { second: { x: .3, y: .4 } } }),
      ])

      expect([first.statusCode, second.statusCode].sort()).toEqual([200, 409])
      const current = await request('GET')
      // Exactly one request was allowed to establish the next revision. In
      // particular, the losing request did not silently overwrite the file.
      expect(Object.keys(current.body.geometry)).toHaveLength(1)
      expect(['first', 'second']).toContain(Object.keys(current.body.geometry)[0])
    }
    finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  it('refuses an output path outside the consuming deck root', () => {
    const plugin = drawnAnnotationEditor({ output: '../outside.css' })
    expect(() => plugin.configResolved?.({ root: '/tmp/deck' })).toThrow('must stay under the Vite root')
  })
})
