import { createHash, randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, relative, resolve } from 'node:path'

export interface DrawnAnnotationLabelGeometry {
  x?: number
  y?: number
  width?: number
  /** Manual connector endpoints, as fractions of the concrete slide. */
  x1?: number
  y1?: number
  x2?: number
  y2?: number
}

/** `null` deletes one property; a null annotation deletes its complete rule. */
export type DrawnAnnotationGeometryPatch = Record<string, Partial<Record<keyof DrawnAnnotationLabelGeometry, number | null>> | null>

export interface DrawnAnnotationEditorOptions {
  /** Generated stylesheet path, relative to the consuming deck root. */
  output?: string
}

export const DRAWN_ANNOTATION_ID = /^[A-Za-z][A-Za-z0-9_.-]*$/
const HEADER = '/* Generated by the DrawnAnnotation editor. Do not edit while Slidev is running. */'
const MAX_BODY_BYTES = 64 * 1024

function validFraction(value: unknown, minimum = 0): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value >= minimum && value <= 1
}

/** Rejects unknown keys too, so browser input can never turn into arbitrary CSS. */
export function validateGeometryPatch(value: unknown): DrawnAnnotationGeometryPatch {
  if (!value || typeof value !== 'object' || Array.isArray(value))
    throw new Error('annotations must be an object keyed by annotation ID')

  const result: DrawnAnnotationGeometryPatch = {}
  for (const [id, geometry] of Object.entries(value)) {
    if (!DRAWN_ANNOTATION_ID.test(id))
      throw new Error(`invalid annotation ID: ${JSON.stringify(id)}`)
    if (geometry === null) {
      result[id] = null
      continue
    }
    if (!geometry || typeof geometry !== 'object' || Array.isArray(geometry))
      throw new Error(`geometry for ${id} must be an object or null`)
    const candidate = geometry as Record<string, unknown>
    if (Object.keys(candidate).some(key => !['x', 'y', 'width', 'x1', 'y1', 'x2', 'y2'].includes(key)))
      throw new Error(`geometry for ${id} has an unknown property`)
    for (const key of ['x', 'y', 'x1', 'y1', 'x2', 'y2']) {
      if (candidate[key] !== undefined && candidate[key] !== null && !validFraction(candidate[key]))
        throw new Error(`${key} for ${id} must be a finite fraction from 0 to 1`)
    }
    if (candidate.width !== undefined && candidate.width !== null && !validFraction(candidate.width, 0.02))
      throw new Error(`width for ${id} must be a finite fraction from 0.02 to 1`)
    result[id] = Object.fromEntries(Object.entries(candidate)) as Partial<Record<keyof DrawnAnnotationLabelGeometry, number | null>>
  }
  return result
}

function format(value: number) {
  return value.toFixed(4).replace(/0+$/, '').replace(/\.$/, '')
}

/** Canonical, wholly tool-owned CSS output. */
export function serializeGeometry(geometry: Record<string, DrawnAnnotationLabelGeometry>): string {
  const rules = Object.keys(geometry).sort().flatMap((id) => {
    const item = geometry[id]
    const properties = [
      item.x === undefined ? undefined : `  --da-label-x: ${format(item.x)};`,
      item.y === undefined ? undefined : `  --da-label-y: ${format(item.y)};`,
      item.width === undefined ? undefined : `  --da-label-width: ${format(item.width)};`,
      item.x1 === undefined ? undefined : `  --da-connector-x1: ${format(item.x1)};`,
      item.y1 === undefined ? undefined : `  --da-connector-y1: ${format(item.y1)};`,
      item.x2 === undefined ? undefined : `  --da-connector-x2: ${format(item.x2)};`,
      item.y2 === undefined ? undefined : `  --da-connector-y2: ${format(item.y2)};`,
    ].filter((value): value is string => value !== undefined)
    return properties.length ? [`[data-drawn-annotation-id="${id}"] {`, ...properties, '}'] : []
  })
  return [HEADER, ...(rules.length ? ['', ...rules] : [])].join('\n') + '\n'
}

/** Parses only the serializer's constrained rule shape; malformed rules are ignored. */
export function parseGeometry(css: string): Record<string, DrawnAnnotationLabelGeometry> {
  const result: Record<string, DrawnAnnotationLabelGeometry> = {}
  const rule = /\[data-drawn-annotation-id="([A-Za-z][A-Za-z0-9_.-]*)"\]\s*\{([\s\S]*?)\}/g
  for (const match of css.matchAll(rule)) {
    const declarations = match[2]
    const read = (name: string, minimum = 0) => {
      const found = new RegExp(`${name}\\s*:\\s*([0-9]+(?:\\.[0-9]+)?|\\.[0-9]+)\\s*;`).exec(declarations)
      return found && validFraction(Number(found[1]), minimum) ? Number(found[1]) : undefined
    }
    const geometry = {
      x: read('--da-label-x'), y: read('--da-label-y'), width: read('--da-label-width', 0.02),
      x1: read('--da-connector-x1'), y1: read('--da-connector-y1'),
      x2: read('--da-connector-x2'), y2: read('--da-connector-y2'),
    }
    if (Object.values(geometry).some(value => value !== undefined))
      result[match[1]] = geometry
  }
  return result
}

export function geometryRevision(geometry: Record<string, DrawnAnnotationLabelGeometry>) {
  return createHash('sha256').update(serializeGeometry(geometry)).digest('hex').slice(0, 16)
}

async function readGeometry(path: string) {
  try {
    return parseGeometry(await readFile(path, 'utf8'))
  }
  catch (error: any) {
    if (error?.code === 'ENOENT')
      return {}
    throw error
  }
}

async function writeGeometry(path: string, geometry: Record<string, DrawnAnnotationLabelGeometry>) {
  await mkdir(dirname(path), { recursive: true })
  const temporary = `${path}.${randomUUID()}.tmp`
  try {
    await writeFile(temporary, serializeGeometry(geometry), 'utf8')
    await rename(temporary, path)
  }
  finally {
    await unlink(temporary).catch(() => {})
  }
}

function json(response: any, status: number, body: unknown) {
  response.statusCode = status
  response.setHeader('Content-Type', 'application/json; charset=utf-8')
  response.end(JSON.stringify(body))
}

async function requestBody(request: any): Promise<unknown> {
  const chunks: Buffer[] = []
  let length = 0
  for await (const chunk of request) {
    length += chunk.length
    if (length > MAX_BODY_BYTES)
      throw new Error('request body is too large')
    chunks.push(chunk)
  }
  try { return JSON.parse(Buffer.concat(chunks).toString('utf8')) }
  catch { throw new Error('request body must be JSON') }
}

/**
 * Development-only Vite plugin. It deliberately exposes a narrow JSON API
 * rather than accepting paths or CSS from the browser.
 */
export function drawnAnnotationEditor(options: DrawnAnnotationEditorOptions = {}) {
  let output = ''
  return {
    name: 'slidev-theme-kotlin:drawn-annotation-editor',
    apply: 'serve' as const,
    configResolved(config: { root: string }) {
      const configured = options.output ?? 'styles/drawn-annotations.generated.css'
      output = resolve(config.root, configured)
      if (isAbsolute(configured) || (relative(config.root, output).startsWith('..')))
        throw new Error('drawnAnnotationEditor output must stay under the Vite root')
    },
    configureServer(server: { middlewares: { use: (handler: Function) => void } }) {
      server.middlewares.use(async (request: any, response: any, next: Function) => {
        if (new URL(request.url ?? '/', 'http://localhost').pathname !== '/__drawn-annotations')
          return next()
        try {
          const geometry = await readGeometry(output)
          const revision = geometryRevision(geometry)
          if (request.method === 'GET')
            return json(response, 200, { geometry, revision })
          if (request.method !== 'POST')
            return json(response, 405, { error: 'use GET or POST' })
          const payload = await requestBody(request) as { expectedRevision?: unknown, annotations?: unknown }
          if (payload.expectedRevision !== revision)
            return json(response, 409, { error: 'geometry changed; reload before saving', geometry, revision })
          const patch = validateGeometryPatch(payload.annotations)
          const nextGeometry = { ...geometry }
          for (const [id, value] of Object.entries(patch)) {
            if (value === null) {
              delete nextGeometry[id]
              continue
            }
            // Patches are property-wise: moving a label must not accidentally
            // erase its already-saved width or the other coordinate. Null is
            // the explicit counterpart for toolbar reset actions.
            const next = { ...nextGeometry[id] }
            for (const [key, property] of Object.entries(value)) {
              if (property === null)
                delete next[key as keyof DrawnAnnotationLabelGeometry]
              else
                next[key as keyof DrawnAnnotationLabelGeometry] = property
            }
            if (Object.keys(next).length)
              nextGeometry[id] = next
            else
              delete nextGeometry[id]
          }
          await writeGeometry(output, nextGeometry)
          return json(response, 200, { geometry: nextGeometry, revision: geometryRevision(nextGeometry) })
        }
        catch (error: any) {
          return json(response, 400, { error: error instanceof Error ? error.message : 'unable to save annotation geometry' })
        }
      })
    },
  }
}
