import { describe, expect, it } from 'vitest'
import { geometryRevision, parseGeometry, serializeGeometry, validateGeometryPatch } from './drawn-annotation-editor'

describe('DrawnAnnotation editor writer format', () => {
  it('serializes in a stable order with fixed precision', () => {
    const geometry = {
      zebra: { y: .2, x: .123456, width: .5 },
      alpha: { x: 1 },
    }
    expect(serializeGeometry(geometry)).toBe(`/* Generated by the DrawnAnnotation editor. Do not edit while Slidev is running. */

[data-drawn-annotation-id="alpha"] {
  --da-label-x: 1;
}
[data-drawn-annotation-id="zebra"] {
  --da-label-x: 0.1235;
  --da-label-y: 0.2;
  --da-label-width: 0.5;
}
`)
    expect(parseGeometry(serializeGeometry(geometry))).toEqual({
      alpha: { x: 1, y: undefined, width: undefined, x1: undefined, y1: undefined, x2: undefined, y2: undefined },
      zebra: { x: .1235, y: .2, width: .5, x1: undefined, y1: undefined, x2: undefined, y2: undefined },
    })
    expect(geometryRevision(geometry)).toBe(geometryRevision({ alpha: { x: 1 }, zebra: { x: .123456, y: .2, width: .5 } }))
  })

  it('only accepts safe IDs, known fields, and usable geometry', () => {
    expect(validateGeometryPatch({ okay: { x: 0, y: 1, width: .02, x1: .1, y1: .2, x2: .3, y2: .4 }, removed: null })).toEqual({ okay: { x: 0, y: 1, width: .02, x1: .1, y1: .2, x2: .3, y2: .4 }, removed: null })
    expect(validateGeometryPatch({ okay: { x: null, y: null, width: null } })).toEqual({ okay: { x: null, y: null, width: null } })
    expect(() => validateGeometryPatch({ 'not safe': { x: .5 } })).toThrow('invalid annotation ID')
    expect(() => validateGeometryPatch({ okay: { x: .5, css: 'nope' } })).toThrow('unknown property')
    expect(() => validateGeometryPatch({ okay: { width: .01 } })).toThrow('width')
    expect(() => validateGeometryPatch({ okay: { x: Number.NaN } })).toThrow('x')
  })

  it('round-trips manual connector endpoints and ignores malformed generated rules', () => {
    expect(parseGeometry('[data-drawn-annotation-id="okay"] { --da-label-x: 2; }\n[data-drawn-annotation-id="good"] { --da-label-y: .5; --da-connector-x1: .1; --da-connector-y1: .2; --da-connector-x2: .3; --da-connector-y2: .4; }')).toEqual({ good: { x: undefined, y: .5, width: undefined, x1: .1, y1: .2, x2: .3, y2: .4 } })
  })
})
